--drop table if exists tableGame1;
    create table tableGame1 (record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id none, 
    que1_rc1 int, 
    que1_rc2 int, 
    que1_rc3 int, 
    que1_rc4 int, 
    que1_rc5 int, 
    que1_rc6 int, 
    que1_rc7 int, 
    que1_rc8 int, 
    que1_rc9 int, 
    que1_rc10 int, 
    que2_rc1 int, 
    que2_rc2 int, 
    que2_rc3 int, 
    que2_rc4 int, 
    que2_rc5 int, 
    que2_rc6 int, 
    que2_rc7 int, 
    que2_rc8 int, 
    que2_rc9 int, 
    que2_rc10 int
);