-- drop table if exists tableGame2;
    create table tableGame2 (record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id none,
    o1_c1 int,
    o1_c2 int, 
    o1_c3 int, 
    o1_c4 int, 
    o1_c5 int, 
    o1_c6 int, 
    o1_c7 int, 
    o1_c8 int, 
    o1_c9 int, 
    o1_c10 int,
    o2_c1 int,
    o2_c2 int, 
    o2_c3 int, 
    o2_c4 int, 
    o2_c5 int, 
    o2_c6 int, 
    o2_c7 int, 
    o2_c8 int, 
    o2_c9 int, 
    o2_c10 int
);